# SPDX-FileCopyrightText: 2026 Stagelab Coop SCCL
# SPDX-License-Identifier: GPL-3.0-or-later
"""T020 — the upgrade's ordering is enforced, not claimed (FR-012, FR-013, SC-007, SC-008).

``debian/postinst`` used to defer its conversion-versus-restart ordering to "feature 008",
a feature that closed and was renumbered. This test pins the decision that replaced
that deferral, against the script itself:

* the network-map conversion runs before every in-script reader of the converted
  map, and before the live discovery-file migration;
* the premise of the decision still holds — this ``postinst`` has no ``#DEBHELPER#``
  token, so ``dh_installsystemd`` injects no service restarts into it. If that
  ever changes, the recorded decision is wrong and this test says so;
* no maintainer script defers a decision to a feature number again. A provenance
  label naming the feature that introduced a block — ``(feature 007, M3)`` — is
  not a deferral and stays allowed.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DEBIAN = REPO_ROOT / "debian"
POSTINST = DEBIAN / "postinst"
MAINTAINER_SCRIPTS = sorted(
    p for p in DEBIAN.iterdir() if p.name in {"preinst", "postinst", "prerm", "postrm", "config"}
)

#: Postponing phrasing followed by a feature number, as FR-013 defines a deferral.
DEFERRAL = re.compile(
    r"\b(?:deferred|defer|left|postponed|pushed|moved)\s+(?:to|for|until)\s+feature\s+\d+"
    r"|\buntil\s+feature\s+\d+",
    re.I,
)


def _code_lines(path: Path) -> list[tuple[int, str]]:
    return [
        (n, line)
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1)
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _first_code_line(path: Path, pattern: str) -> int:
    for n, line in _code_lines(path):
        if re.search(pattern, line):
            return n
    pytest.fail(f"{path.name}: no code line matches {pattern!r}")


def _comment_prose(path: Path) -> str:
    """All comment text joined into one string, so a phrase split across
    ``# ...`` lines is still seen as one phrase."""
    parts = [
        re.sub(r"^\s*#\s?", "", line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.lstrip().startswith("#")
    ]
    return re.sub(r"\s+", " ", " ".join(parts))


def test_network_map_conversion_precedes_every_in_script_reader():
    conversion = _first_code_line(POSTINST, r"/usr/bin/cuems-migrate-network-map\s+\"\$f\"")
    chrony_reader = _first_code_line(POSTINST, r"^/usr/lib/cuems/bin/cuems-write-chrony-source\b")
    assert conversion < chrony_reader


def test_network_map_conversion_precedes_the_discovery_migration():
    conversion = _first_code_line(POSTINST, r"/usr/bin/cuems-migrate-network-map\s+\"\$f\"")
    discovery = _first_code_line(POSTINST, r"/usr/bin/cuems-migrate-avahi-service\s+/etc/avahi/")
    assert conversion < discovery


def test_the_decisions_premise_still_holds():
    # The recorded decision rests on this: no autogenerated restarts in postinst.
    assert "#DEBHELPER#" not in POSTINST.read_text(encoding="utf-8")
    assert "#DEBHELPER#" in (DEBIAN / "preinst").read_text(encoding="utf-8")


@pytest.mark.parametrize("script", MAINTAINER_SCRIPTS, ids=lambda p: p.name)
def test_no_maintainer_script_defers_a_decision_to_a_feature_number(script):
    found = DEFERRAL.findall(_comment_prose(script))
    assert found == [], f"{script.name} defers to a feature number: {found}"


def test_provenance_labels_are_not_deferrals():
    assert not DEFERRAL.search("network_map.xml node_type -> node_role conversion (feature 007, M3)")
    assert DEFERRAL.search("whose ordering is deferred to feature 008")
    assert DEFERRAL.search("left for feature 012 to decide")
